name: Deploy Backend

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name : Backup .env
        run: 
          if [ -f .env ]: then mv .env /tmp/env_backup: fi
      
      - name: Checkout code
        uses: actions/checkout@v4

      - name : Restore .env 
        run :
          if [ -f /tmp/env_backup ]: then mv /tmp/env_backup .env :fi

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Restart server
        run: |
          pm2 restart server || pm2 start server.js --name server
          pm2 save
